---
services: docker

env:
  - distro: centos7
  - distro: ubuntu1604
  - distro: ubuntu1404
  - distro: debian8
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - docker --version

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

# notifications:
#   email: false
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
