---
- name: Grid Router | Install certain python modules for docker
  pip:
    name: "{{ item.name }}"
  with_items:
  - { name: docker-py }
  - { name: passlib }

- debug:
    msg: Ggr home is {{ grid_router_quota_path }}

- name: Grid Router | Create config dir
  file:
    path: "{{ grid_router_quota_path }}"
    state: directory
    mode: 0755

- name: Copy quota file
  copy:
    src: "{{ quota_file }}"
    dest: "{{ grid_router_quota_path }}"

- name: Grid Router | Setup quota password
  htpasswd:
    path: "{{ grid_router_path }}/users.htpasswd"
    name: "{{ grid_router_quota_user }}"
    password: "{{ grid_router_quota_password}}"
    mode: 0640

- name: Grid Router | Run Grid Router container
  docker_container:
    name: grid_router
    restart_policy: always
    image: "aerokube/ggr:{{ grid_router_version }}"
    network_mode: host
    state: started
    volumes:
    - "{{ grid_router_path }}:/etc/grid-router:ro"
    env:
      TZ: "{{ grid_router_time_zone }}"
      DOCKER_API_VERSION: "{{ grid_router_docker_api_version }}"
    ports:
    - "{{ grid_router_port }}:4444"
    
- name: Reload GGR
  shell: "docker kill -s HUP grid_router"

- name: Run ggr-ui
  docker_container:
    name: ggr-ui
    restart_policy: always
    image: "aerokube/ggr-ui:latest-release"
    state: started
    volumes:
    - "{{ grid_router_quota_path }}:/etc/grid-router/quota:ro"
    ports:
    - "8888:8888"

- name: Reload GGR-UI
  shell: "docker kill -s HUP ggr-ui"